import type { Project, Builder, AppSettings } from "@/types";

// ─── Seed Builders ────────────────────────────────────────────────────────────

export const SEED_BUILDERS: Builder[] = [
  {
    builderId: "dsr",
    builderName: "DSR Infrastructure",
    builderGroupName: "DSR Group",
    builderWebsite: "https://dsrinfrastructure.com",
    logoInitials: "DSR",
    logoColor: "#1e40af",
    primarySalesContactName: "Sales Team",
    primarySalesContactPhone: "+91 80 4000 0000",
    builderCredibilityRating: 7,
    pastDeliveryReputation: "Good track record in East Bangalore with several delivered projects.",
    constructionQualityReputation: "Above average. Good use of branded fittings.",
    resaleLiquidityPerception: "Medium",
    builderRiskLevel: "Low",
    builderGallery: [],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    builderId: "myhna",
    builderName: "Myhna Group",
    builderWebsite: "https://myhnagroup.com",
    logoInitials: "MYH",
    logoColor: "#059669",
    primarySalesContactName: "Sales Team",
    builderCredibilityRating: 6,
    pastDeliveryReputation: "Delivered previous projects in Varthur area.",
    resaleLiquidityPerception: "Medium",
    builderRiskLevel: "Low",
    builderGallery: [],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    builderId: "sanjeevini",
    builderName: "Sanjeevini Developers",
    builderWebsite: "https://sanjeevinibuilders.com",
    logoInitials: "SAN",
    logoColor: "#7c3aed",
    primarySalesContactName: "Sales Team",
    builderCredibilityRating: 6,
    resaleLiquidityPerception: "Medium",
    builderRiskLevel: "Medium",
    builderGallery: [],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    builderId: "earthscape",
    builderName: "Earthscape Developers",
    logoInitials: "EAR",
    logoColor: "#b45309",
    builderCredibilityRating: 7,
    resaleLiquidityPerception: "High",
    builderRiskLevel: "Low",
    builderGallery: [],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
];

// ─── Seed Projects ────────────────────────────────────────────────────────────

export const SEED_PROJECTS: Project[] = [
  {
    projectId: "earthscape-001",
    projectName: "The Earthscape",
    projectDisplayName: "The Earthscape",
    projectShortName: "Earthscape",
    builderId: "earthscape",
    builderName: "Earthscape Developers",
    projectType: "Apartment",
    projectPurpose: "Both",
    projectStatus: "Shortlisted",
    city: "Bangalore",
    cityZone: "East Bangalore",
    microMarket: "Varthur",
    locality: "Varthur Road, Whitefield",
    address: "Varthur Road, Whitefield, Bangalore - 560066",
    latitude: 12.9352,
    longitude: 77.7244,
    reraNumber: "PRM/KA/RERA/1251/309/PR/210601/003824",
    reraStatus: "Registered",
    totalLandAreaAcres: 8.5,
    totalTowers: 4,
    totalFloors: 20,
    totalUnits: 480,
    openSpacePercentage: 72,
    estimatedPossessionDate: "2026-12-31",
    possessionConfidence: "Builder Provided",
    priceRangeMinPerSqft: 7200,
    priceRangeMaxPerSqft: 8500,
    indicativePriceMin: 9000000,
    indicativePriceMax: 15000000,
    availableBHKs: ["2BHK", "3BHK", "3.5BHK"],
    sourceOfLead: "Builder Website",
    sourceUrl: "https://earthscapedevelopers.com",
    images: [
      {
        id: "es-img-1",
        url: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
        caption: "The Earthscape — Main Elevation",
        category: "hero",
        isCover: true,
        sortOrder: 1,
        addedAt: "2024-01-01T00:00:00Z",
      },
      {
        id: "es-img-2",
        url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
        caption: "Clubhouse & Swimming Pool",
        category: "amenity-photo",
        sortOrder: 2,
        addedAt: "2024-01-01T00:00:00Z",
      },
      {
        id: "es-img-3",
        url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
        caption: "Tower A — Elevation Render",
        category: "elevation",
        sortOrder: 3,
        addedAt: "2024-01-01T00:00:00Z",
      },
      {
        id: "es-img-4",
        url: "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=800&q=80",
        caption: "Master Plan Overview",
        category: "master-plan",
        sortOrder: 4,
        addedAt: "2024-01-01T00:00:00Z",
      },
      {
        id: "es-fp-1",
        url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
        caption: "3BHK Floor Plan — Tower A",
        category: "floor-plan",
        unitType: "3BHK",
        towerName: "Tower A",
        sortOrder: 5,
        addedAt: "2024-01-01T00:00:00Z",
      },
      {
        id: "es-fp-2",
        url: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&q=80",
        caption: "2BHK Floor Plan — Tower B",
        category: "floor-plan",
        unitType: "2BHK",
        towerName: "Tower B",
        sortOrder: 6,
        addedAt: "2024-01-01T00:00:00Z",
      },
    ],
    videos: [
      {
        id: "es-vid-1",
        rawUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        embedUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        platform: "youtube",
        videoType: "walkthrough",
        title: "The Earthscape — Property Walkthrough",
        addedAt: "2024-01-01T00:00:00Z",
      },
    ],
    documents: [
      {
        id: "es-doc-1",
        url: "#",
        name: "The Earthscape — Brochure 2024",
        type: "brochure",
        projectId: "earthscape-001",
        collectionStatus: "Collected",
        verificationStatus: "Reviewed",
        addedAt: "2024-01-01T00:00:00Z",
      },
    ],
    brochureCollected: true,
    floorPlansCollected: true,
    masterPlanCollected: true,
    reraCertificateCollected: true,
    amenities: [
      { id: "a1", name: "Swimming Pool", category: "Wellness", available: true },
      { id: "a2", name: "Gymnasium", category: "Wellness", available: true },
      { id: "a3", name: "Clubhouse", category: "Social", available: true },
      { id: "a4", name: "Children Play Area", category: "Children", available: true },
      { id: "a5", name: "Landscaped Gardens", category: "Green", available: true },
      { id: "a6", name: "24/7 Security", category: "Security", available: true },
      { id: "a7", name: "EV Charging", category: "Utilities", available: true },
      { id: "a8", name: "Co-working Space", category: "Social", available: true },
      { id: "a9", name: "Badminton Court", category: "Sports", available: true },
    ],
    projectHighlights: [
      "RERA registered project",
      "72% open spaces",
      "Vastu-compliant units",
      "EV charging provision",
      "Premium specifications",
      "Walking distance to tech parks",
    ],
    riskLevel: "Low",
    notes: "Strong shortlist candidate. Good carpet efficiency reported.",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    projectId: "dsr-courtyard-001",
    projectName: "DSR Courtyard",
    projectDisplayName: "DSR Courtyard",
    projectShortName: "DSR Courtyard",
    builderId: "dsr",
    builderName: "DSR Infrastructure",
    projectType: "Apartment",
    projectPurpose: "Living",
    projectStatus: "Under Comparison",
    city: "Bangalore",
    cityZone: "East Bangalore",
    microMarket: "Whitefield",
    locality: "ITPL Road, Whitefield",
    address: "ITPL Road, Whitefield, Bangalore - 560048",
    latitude: 12.9801,
    longitude: 77.7258,
    reraNumber: "PRM/KA/RERA/1251/309/PR/220301/004512",
    reraStatus: "Registered",
    totalLandAreaAcres: 5.2,
    totalTowers: 3,
    totalFloors: 18,
    totalUnits: 312,
    openSpacePercentage: 65,
    estimatedPossessionDate: "2027-06-30",
    possessionConfidence: "Builder Provided",
    priceRangeMinPerSqft: 8000,
    priceRangeMaxPerSqft: 9500,
    indicativePriceMin: 10500000,
    indicativePriceMax: 17000000,
    availableBHKs: ["2BHK", "3BHK"],
    sourceOfLead: "Referral",
    images: [
      {
        id: "dsr-img-1",
        url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80",
        caption: "DSR Courtyard — Aerial View",
        category: "hero",
        isCover: true,
        sortOrder: 1,
        addedAt: "2024-01-01T00:00:00Z",
      },
      {
        id: "dsr-img-2",
        url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
        caption: "Central Courtyard",
        category: "gallery",
        sortOrder: 2,
        addedAt: "2024-01-01T00:00:00Z",
      },
      {
        id: "dsr-img-3",
        url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
        caption: "Tower Elevation",
        category: "elevation",
        sortOrder: 3,
        addedAt: "2024-01-01T00:00:00Z",
      },
      {
        id: "dsr-fp-1",
        url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
        caption: "3BHK Floor Plan",
        category: "floor-plan",
        unitType: "3BHK",
        sortOrder: 4,
        addedAt: "2024-01-01T00:00:00Z",
      },
    ],
    videos: [],
    documents: [
      {
        id: "dsr-doc-1",
        url: "#",
        name: "DSR Courtyard — Brochure",
        type: "brochure",
        projectId: "dsr-courtyard-001",
        collectionStatus: "Collected",
        verificationStatus: "Reviewed",
        addedAt: "2024-01-01T00:00:00Z",
      },
    ],
    brochureCollected: true,
    floorPlansCollected: true,
    masterPlanCollected: false,
    reraCertificateCollected: true,
    amenities: [
      { id: "b1", name: "Swimming Pool", category: "Wellness", available: true },
      { id: "b2", name: "Gymnasium", category: "Wellness", available: true },
      { id: "b3", name: "Clubhouse", category: "Social", available: true },
      { id: "b4", name: "Children Play Area", category: "Children", available: true },
      { id: "b5", name: "24/7 Security", category: "Security", available: true },
      { id: "b6", name: "Tennis Court", category: "Sports", available: true },
    ],
    projectHighlights: [
      "RERA registered",
      "DSR track record",
      "Central courtyard design",
      "Close to ITPL tech park",
      "Good connectivity",
    ],
    riskLevel: "Low",
    notes: "Parking details need confirmation.",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    projectId: "myhna-orchid-001",
    projectName: "Myhna Orchid",
    projectDisplayName: "Myhna Orchid",
    projectShortName: "Myhna Orchid",
    builderId: "myhna",
    builderName: "Myhna Group",
    projectType: "Apartment",
    projectPurpose: "Both",
    projectStatus: "Site Visited",
    city: "Bangalore",
    cityZone: "East Bangalore",
    microMarket: "Varthur",
    locality: "Varthur Hobli",
    address: "Varthur Hobli, East Bangalore - 560087",
    latitude: 12.9274,
    longitude: 77.7434,
    reraNumber: "PRM/KA/RERA/1251/446/PR/230101/005100",
    reraStatus: "Registered",
    totalLandAreaAcres: 4.8,
    totalTowers: 2,
    totalFloors: 15,
    totalUnits: 240,
    openSpacePercentage: 68,
    estimatedPossessionDate: "2027-03-31",
    possessionConfidence: "Builder Provided",
    priceRangeMinPerSqft: 6800,
    priceRangeMaxPerSqft: 7800,
    indicativePriceMin: 8500000,
    indicativePriceMax: 13000000,
    availableBHKs: ["2BHK", "3BHK"],
    sourceOfLead: "Builder Website",
    images: [
      {
        id: "mo-img-1",
        url: "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=1200&q=80",
        caption: "Myhna Orchid — Front View",
        category: "hero",
        isCover: true,
        sortOrder: 1,
        addedAt: "2024-01-01T00:00:00Z",
      },
      {
        id: "mo-img-2",
        url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80",
        caption: "Garden & Landscape",
        category: "amenity-photo",
        sortOrder: 2,
        addedAt: "2024-01-01T00:00:00Z",
      },
      {
        id: "mo-fp-1",
        url: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&q=80",
        caption: "2BHK Floor Plan",
        category: "floor-plan",
        unitType: "2BHK",
        sortOrder: 3,
        addedAt: "2024-01-01T00:00:00Z",
      },
    ],
    videos: [],
    documents: [],
    brochureCollected: false,
    floorPlansCollected: true,
    masterPlanCollected: false,
    reraCertificateCollected: false,
    amenities: [
      { id: "c1", name: "Swimming Pool", category: "Wellness", available: true },
      { id: "c2", name: "Gymnasium", category: "Wellness", available: true },
      { id: "c3", name: "Clubhouse", category: "Social", available: true },
      { id: "c4", name: "Children Play Area", category: "Children", available: true },
      { id: "c5", name: "24/7 Security", category: "Security", available: true },
    ],
    projectHighlights: [
      "Affordable pricing in East Bangalore",
      "Good open space ratio",
      "RERA registered",
    ],
    riskLevel: "Medium",
    notes: "RERA certificate not yet collected. Brochure pending.",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    projectId: "dsr-address-001",
    projectName: "DSR The Address",
    projectDisplayName: "DSR The Address",
    projectShortName: "DSR Address",
    builderId: "dsr",
    builderName: "DSR Infrastructure",
    projectType: "Apartment",
    projectPurpose: "Investment",
    projectStatus: "Watchlist",
    city: "Bangalore",
    cityZone: "East Bangalore",
    microMarket: "Sarjapur Road",
    locality: "Sarjapur Road, Carmelaram",
    address: "Sarjapur Road, Carmelaram, Bangalore - 560035",
    latitude: 12.9009,
    longitude: 77.7012,
    reraStatus: "Awaited",
    totalTowers: 5,
    totalFloors: 22,
    totalUnits: 600,
    estimatedPossessionDate: "2028-12-31",
    possessionConfidence: "User Estimate",
    priceRangeMinPerSqft: 9000,
    priceRangeMaxPerSqft: 11000,
    indicativePriceMin: 12000000,
    indicativePriceMax: 20000000,
    availableBHKs: ["2BHK", "3BHK", "4BHK"],
    sourceOfLead: "Builder Website",
    images: [
      {
        id: "da-img-1",
        url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=1200&q=80",
        caption: "DSR The Address — Rendering",
        category: "hero",
        isCover: true,
        sortOrder: 1,
        addedAt: "2024-01-01T00:00:00Z",
      },
      {
        id: "da-img-2",
        url: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80",
        caption: "Clubhouse Render",
        category: "amenity-photo",
        sortOrder: 2,
        addedAt: "2024-01-01T00:00:00Z",
      },
    ],
    videos: [],
    documents: [],
    brochureCollected: false,
    floorPlansCollected: false,
    masterPlanCollected: false,
    reraCertificateCollected: false,
    amenities: [
      { id: "d1", name: "Swimming Pool", category: "Wellness", available: true },
      { id: "d2", name: "Gymnasium", category: "Wellness", available: true },
      { id: "d3", name: "Clubhouse", category: "Social", available: true },
      { id: "d4", name: "Rooftop Lounge", category: "Social", available: true },
      { id: "d5", name: "EV Charging", category: "Utilities", available: true },
    ],
    projectHighlights: [
      "Premium address on Sarjapur Road",
      "5 towers luxury development",
      "High investment potential",
    ],
    riskLevel: "Medium",
    notes: "RERA awaited. High price point. Good location for investment.",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    projectId: "sanjeevini-adwaith-001",
    projectName: "Sanjeevini Adwaith",
    projectDisplayName: "The Adwaith by Sanjeevini",
    projectShortName: "The Adwaith",
    builderId: "sanjeevini",
    builderName: "Sanjeevini Developers",
    projectType: "Apartment",
    projectPurpose: "Living",
    projectStatus: "Under Comparison",
    city: "Bangalore",
    cityZone: "East Bangalore",
    microMarket: "Whitefield",
    locality: "Kadugodi, Whitefield",
    address: "Kadugodi Main Road, Whitefield, Bangalore - 560067",
    latitude: 12.9986,
    longitude: 77.7583,
    reraNumber: "PRM/KA/RERA/1251/309/PR/230601/005689",
    reraStatus: "Registered",
    totalLandAreaAcres: 3.6,
    totalTowers: 2,
    totalFloors: 14,
    totalUnits: 168,
    openSpacePercentage: 60,
    estimatedPossessionDate: "2026-09-30",
    possessionConfidence: "Builder Provided",
    priceRangeMinPerSqft: 7500,
    priceRangeMaxPerSqft: 8800,
    indicativePriceMin: 9500000,
    indicativePriceMax: 14500000,
    availableBHKs: ["2BHK", "3BHK", "3.5BHK"],
    sourceOfLead: "Broker",
    images: [
      {
        id: "sa-img-1",
        url: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&q=80",
        caption: "The Adwaith — Elevation",
        category: "hero",
        isCover: true,
        sortOrder: 1,
        addedAt: "2024-01-01T00:00:00Z",
      },
      {
        id: "sa-img-2",
        url: "https://images.unsplash.com/photo-1571055107559-3e67626fa8be?w=800&q=80",
        caption: "Amenities Overview",
        category: "amenity-photo",
        sortOrder: 2,
        addedAt: "2024-01-01T00:00:00Z",
      },
      {
        id: "sa-fp-1",
        url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
        caption: "3.5BHK Floor Plan",
        category: "floor-plan",
        unitType: "3.5BHK",
        sortOrder: 3,
        addedAt: "2024-01-01T00:00:00Z",
      },
    ],
    videos: [],
    documents: [],
    brochureCollected: true,
    floorPlansCollected: true,
    masterPlanCollected: false,
    reraCertificateCollected: true,
    amenities: [
      { id: "e1", name: "Swimming Pool", category: "Wellness", available: true },
      { id: "e2", name: "Gymnasium", category: "Wellness", available: true },
      { id: "e3", name: "Clubhouse", category: "Social", available: true },
      { id: "e4", name: "Children Play Area", category: "Children", available: true },
      { id: "e5", name: "24/7 Security", category: "Security", available: true },
      { id: "e6", name: "Yoga Deck", category: "Wellness", available: true },
    ],
    projectHighlights: [
      "Earliest possession — Sep 2026",
      "RERA registered",
      "Boutique project — only 168 units",
      "Close to Whitefield metro",
    ],
    riskLevel: "Low",
    notes: "Closest to possession. Low risk. Good for living.",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
];

export const DEFAULT_SETTINGS: AppSettings = {
  defaultCity: "Bangalore",
  defaultCityZone: "East Bangalore",
  gstDefaultPercentage: 5,
  stampDutyDefaultPercentage: 5.6,
  registrationDefaultPercentage: 1,
};
